In [35]:
import torch

## 测试jupyter

In [36]:
def linear_q_with_scale_and_zero_point(
    tensor,scale,zero_point,dtype=torch.int8):
    scaled_and_shifted_tenfor = tensor / scale + zero_point
    rounded_tensor = torch.round(scaled_and_shifted_tenfor)

    q_min = torch.iinfo(dtype).min
    q_max = torch.iinfo(dtype).max

    q_tensor = rounded_tensor.clamp(q_min, q_max).to(dtype)
    return q_tensor

In [37]:
test_tensor = torch.tensor(
    [[191.6, -13.5, 728.6],
    [92.14, 295.5, -184],
    [0,684.6, 245.5]])

In [38]:
scale = 3.5
zero_point = -70

In [39]:
quantized_tensor = linear_q_with_scale_and_zero_point(test_tensor,scale,zero_point)

In [40]:
quantized_tensor

tensor([[ -15,  -74,  127],
        [ -44,   14, -123],
        [ -70,  126,    0]], dtype=torch.int8)

In [41]:
dequantized_tensor = scale * (quantized_tensor.float() - zero_point)

In [42]:
dequantized_tensor

tensor([[ 192.5000,  -14.0000,  689.5000],
        [  91.0000,  294.0000, -185.5000],
        [   0.0000,  686.0000,  245.0000]])

In [43]:
scale * (quantized_tensor - zero_point)

tensor([[ 192.5000,  -14.0000, -206.5000],
        [  91.0000,  294.0000, -185.5000],
        [   0.0000, -210.0000,  245.0000]])

In [44]:
def linear_dequantization(quantized_tensor, scale, zero_point):
    return scale * (quantized_tensor.float() - zero_point)

In [45]:
from helper import plot_quantization_errors

ImportError: cannot import name 'plot_quantization_errors' from 'helper' (/opt/homebrew/lib/python3.10/site-packages/helper/__init__.py)

In [ ]:
plot_quantization_errors(test_tensor, quantized_tensor, dequantized_tensor)

NameError: name 'plot_quantization_errors' is not defined